version: '3.5'
services:

  postgres-peterfigure:
    image: postgres:9.6-alpine
    container_name: postgres-peterfigure
    networks:
      peterfigure-development:
        aliases:
          - postgres
    restart: on-failure
    healthcheck:
      test: [CMD-SHELL, pg_isready -U postgres]
      interval: 5s
      timeout: 10s
      retries: 5
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password1
      POSTGRES_DB: peterfigure
    volumes:
      - postgres-peterfigure:/var/lib/postgresql/data

networks:
  peterfigure-development:
    name: peterfigure-development

volumes:
  postgres-peterfigure:

